name: Docker Image CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Debug Secrets
        run: |
          echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"
          echo "DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}"

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            57f903fed2d5df108109d9b3ee4aaac21197f385cf41ee88c268cfade232a05d:latest
            57f903fed2d5df108109d9b3ee4aaac21197f385cf41ee88c268cfade232a05d:${{ github.run_number }}

      - name: Run Docker image
        run: docker run 57f903fed2d5df108109d9b3ee4aaac21197f385cf41ee88c268cfade232a05d:${{ github.run_number }}
