# Generated by Django 4.2.5 on 2023-09-18 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Clan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clan_name", models.CharField(max_length=250)),
                ("description", models.CharField(max_length=250)),
                ("clan_seat", models.CharField(max_length=250)),
                ("clan_history", models.CharField(max_length=250)),
                ("clan_leader_title", models.CharField(max_length=250)),
                ("clan_leader_name", models.CharField(max_length=250)),
                ("cultural_sites", models.CharField(max_length=250)),
                ("totem", models.CharField(max_length=250)),
                ("secondary_totem", models.CharField(max_length=250)),
                ("common_male_names", models.CharField(max_length=250)),
                ("common_female_names", models.CharField(max_length=250)),
                ("special_names", models.CharField(max_length=250)),
                ("taboos", models.CharField(max_length=250)),
                ("spirituality", models.CharField(max_length=250)),
                ("known_headgod", models.CharField(max_length=250)),
                ("known_deities", models.CharField(max_length=250)),
                ("images", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "videos",
                    models.FileField(blank=True, null=True, upload_to="media_files"),
                ),
                (
                    "audio",
                    models.FileField(blank=True, null=True, upload_to="media_files"),
                ),
                ("citation", models.CharField(max_length=250)),
                ("date_entered", models.DateTimeField(auto_now_add=True)),
                (
                    "contributor_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cultural_Kingdom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tribe_name", models.CharField(max_length=250)),
                ("title_of_leader", models.CharField(max_length=250)),
                ("current_king", models.CharField(max_length=250)),
                ("current_chief_name", models.CharField(max_length=250)),
                ("images", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "videos",
                    models.FileField(blank=True, null=True, upload_to="media_files"),
                ),
                (
                    "audio",
                    models.FileField(blank=True, null=True, upload_to="media_files"),
                ),
                ("number_of_clans", models.IntegerField(default=1, null=True)),
                (
                    "clan_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cultures_app.clan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ethnic_Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ethnical_group_name", models.CharField(max_length=250)),
                ("region_in_Uganda", models.CharField(max_length=250)),
                ("number_of_tribes", models.IntegerField(default=1, null=True)),
                ("number_of_languages", models.IntegerField(default=1, null=True)),
                ("number_of_kingdoms", models.IntegerField(default=1, null=True)),
                ("tribe_name", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Tribe",
            fields=[
                (
                    "tribe_name",
                    models.CharField(max_length=250, primary_key=True, serialize=False),
                ),
                ("region_in_Uganda", models.CharField(max_length=250)),
                ("language", models.CharField(max_length=250)),
                ("food", models.CharField(max_length=250)),
                ("staple_food", models.CharField(max_length=250)),
                ("cuisine", models.CharField(max_length=250)),
                ("cashcrop", models.CharField(max_length=250)),
                ("economic_activity", models.CharField(max_length=250)),
                ("universal_worship", models.CharField(max_length=250)),
                ("denominations", models.CharField(max_length=250)),
                ("universal_rituals", models.CharField(max_length=250)),
                ("ceremonies", models.CharField(max_length=250)),
                ("chiefdom", models.CharField(max_length=250)),
                ("images", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "videos",
                    models.FileField(blank=True, null=True, upload_to="media_files"),
                ),
                (
                    "audio",
                    models.FileField(blank=True, null=True, upload_to="media_files"),
                ),
                ("citation", models.CharField(max_length=250)),
                ("date_entered", models.DateTimeField(auto_now_add=True)),
                (
                    "contributor_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kingdom",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cultures_app.cultural_kingdom",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cultural_Identity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ethnic_group", models.CharField(max_length=250)),
                ("notes", models.CharField(max_length=250)),
                ("images", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "videos",
                    models.FileField(blank=True, null=True, upload_to="media_files"),
                ),
                (
                    "audio",
                    models.FileField(blank=True, null=True, upload_to="media_files"),
                ),
                ("citation", models.CharField(max_length=250)),
                (
                    "contributor_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tribe_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cultures_app.tribe",
                    ),
                ),
            ],
            options={
                "ordering": ["ethnic_group"],
            },
        ),
    ]
