# Generated by Django 4.2.6 on 2023-12-01 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan_name', models.CharField(blank=True, max_length=250, null=True)),
                ('clan_seat', models.CharField(blank=True, max_length=250, null=True)),
                ('totem', models.CharField(blank=True, max_length=250, null=True)),
                ('secondary_totem', models.CharField(blank=True, max_length=250, null=True)),
                ('clan_history', models.TextField(blank=True, null=True)),
                ('clan_leader_title', models.CharField(blank=True, max_length=250, null=True)),
                ('clan_leader_name', models.CharField(blank=True, max_length=250, null=True)),
                ('cultural_sites', models.TextField(blank=True, null=True)),
                ('male_names', models.TextField(blank=True, null=True)),
                ('female_names', models.TextField(blank=True, null=True)),
                ('reserved_male_names', models.TextField(blank=True, null=True)),
                ('reserved_female_names', models.TextField(blank=True, null=True)),
                ('taboos', models.CharField(blank=True, max_length=250, null=True)),
                ('lead_god', models.CharField(blank=True, max_length=250, null=True)),
                ('other_gods', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CulturalKingdom',
            fields=[
                ('kingdom_name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('title_of_leader', models.CharField(blank=True, max_length=250, null=True)),
                ('current_king', models.CharField(blank=True, max_length=250, null=True)),
                ('current_chief_name', models.CharField(blank=True, max_length=250, null=True)),
                ('number_of_clans', models.IntegerField(default=1, null=True)),
                ('clan_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultures_app.clan')),
            ],
        ),
        migrations.CreateModel(
            name='Ethnicity',
            fields=[
                ('ethnicity_name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('region_in_Uganda', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=250, null=True)),
                ('food', models.CharField(blank=True, max_length=250, null=True)),
                ('staple_food', models.CharField(blank=True, max_length=250, null=True)),
                ('cuisine', models.CharField(blank=True, max_length=250, null=True)),
                ('cashcrop', models.CharField(blank=True, max_length=250, null=True)),
                ('universal_worship', models.CharField(blank=True, max_length=250, null=True)),
                ('denominations', models.CharField(blank=True, max_length=250, null=True)),
                ('universal_rituals', models.CharField(blank=True, max_length=250, null=True)),
                ('ceremonies', models.CharField(blank=True, max_length=250, null=True)),
                ('chiefdom', models.CharField(blank=True, max_length=250, null=True)),
                ('kingdom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultures_app.culturalkingdom')),
            ],
        ),
        migrations.CreateModel(
            name='EthnicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ethnic_group_name', models.CharField(blank=True, max_length=250, null=True)),
                ('region_in_Uganda', models.CharField(blank=True, max_length=250, null=True)),
                ('number_of_ethnicities', models.IntegerField(blank=True, default=1, null=True)),
                ('number_of_languages', models.IntegerField(default=1, null=True)),
                ('number_of_kingdoms', models.IntegerField(default=1, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='culture_images')),
                ('video', models.FileField(blank=True, null=True, upload_to='culture_videos')),
                ('audio', models.FileField(blank=True, null=True, upload_to='culture_audio')),
                ('citation', models.TextField(blank=True, null=True)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('contributor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ethnicity_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultures_app.ethnicity')),
            ],
        ),
        migrations.CreateModel(
            name='CulturalIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='culture_images')),
                ('video', models.FileField(blank=True, null=True, upload_to='culture_videos')),
                ('audio', models.FileField(blank=True, null=True, upload_to='culture_audio')),
                ('citation', models.TextField(blank=True, null=True)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('contributor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ethnic_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cultures_app.ethnicgroup')),
            ],
        ),
    ]
