# Generated by Django 4.2.6 on 2023-11-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultures_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clan',
            name='images',
        ),
        migrations.RemoveField(
            model_name='clan',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='culturalidentity',
            name='images',
        ),
        migrations.RemoveField(
            model_name='culturalidentity',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='culturalkingdom',
            name='images',
        ),
        migrations.RemoveField(
            model_name='culturalkingdom',
            name='videos',
        ),
        migrations.AddField(
            model_name='clan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='culture_images'),
        ),
        migrations.AddField(
            model_name='clan',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='culture_videos'),
        ),
        migrations.AddField(
            model_name='culturalidentity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='culture_images'),
        ),
        migrations.AddField(
            model_name='culturalidentity',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='culture_videos'),
        ),
        migrations.AddField(
            model_name='culturalkingdom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='culture_images'),
        ),
        migrations.AddField(
            model_name='culturalkingdom',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='culture_videos'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='culture_audio'),
        ),
        migrations.AlterField(
            model_name='clan',
            name='citation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='clan_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='clan_leader_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='clan_leader_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='clan_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='clan_seat',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='cultural_sites',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='female_names',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='lead_god',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='male_names',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='reserved_female_names',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='reserved_male_names',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='secondary_totem',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='taboos',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='totem',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='culturalidentity',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='culture_audio'),
        ),
        migrations.AlterField(
            model_name='culturalidentity',
            name='citation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='culturalidentity',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='culturalkingdom',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='culture_audio'),
        ),
        migrations.AlterField(
            model_name='culturalkingdom',
            name='current_chief_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='culturalkingdom',
            name='current_king',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='culturalkingdom',
            name='title_of_leader',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ethnicgroup',
            name='ethnic_group_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ethnicgroup',
            name='number_of_ethnicities',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='ethnicgroup',
            name='region_in_Uganda',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ethnicity',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='culture_audio'),
        ),
        migrations.AlterField(
            model_name='ethnicity',
            name='cashcrop',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ethnicity',
            name='ceremonies',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ethnicity',
            name='chiefdom',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ethnicity',
            name='citation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ethnicity',
            name='cuisine',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ethnicity',
            name='denominations',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ethnicity',
            name='food',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ethnicity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='culture_images'),
        ),
        migrations.AlterField(
            model_name='ethnicity',
            name='language',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ethnicity',
            name='region_in_Uganda',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ethnicity',
            name='staple_food',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ethnicity',
            name='universal_rituals',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ethnicity',
            name='universal_worship',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='ethnicity',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='culture_videos'),
        ),
    ]
