# Generated by Django 4.2.5 on 2023-09-20 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cultures_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ethnicity",
            fields=[
                (
                    "ethnicity_name",
                    models.CharField(max_length=250, primary_key=True, serialize=False),
                ),
                ("region_in_Uganda", models.CharField(max_length=250)),
                ("language", models.CharField(max_length=250)),
                ("food", models.CharField(max_length=250)),
                ("staple_food", models.CharField(max_length=250)),
                ("cuisine", models.CharField(max_length=250)),
                ("cashcrop", models.CharField(max_length=250)),
                ("universal_worship", models.CharField(max_length=250)),
                ("denominations", models.CharField(max_length=250)),
                ("universal_rituals", models.CharField(max_length=250)),
                ("ceremonies", models.CharField(max_length=250)),
                ("chiefdom", models.CharField(max_length=250)),
                ("images", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "videos",
                    models.FileField(blank=True, null=True, upload_to="media_files"),
                ),
                (
                    "audio",
                    models.FileField(blank=True, null=True, upload_to="media_files"),
                ),
                ("citation", models.CharField(max_length=250)),
                ("date_entered", models.DateTimeField(auto_now_add=True)),
                (
                    "contributor_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="ethnic_group",
            old_name="ethnical_group_name",
            new_name="ethnic_group_name",
        ),
        migrations.RenameField(
            model_name="ethnic_group",
            old_name="number_of_tribes",
            new_name="number_of_ethnicities",
        ),
        migrations.RemoveField(
            model_name="cultural_identity",
            name="tribe_name",
        ),
        migrations.RemoveField(
            model_name="cultural_kingdom",
            name="id",
        ),
        migrations.RemoveField(
            model_name="cultural_kingdom",
            name="tribe_name",
        ),
        migrations.RemoveField(
            model_name="ethnic_group",
            name="tribe_name",
        ),
        migrations.AddField(
            model_name="cultural_identity",
            name="date_entered",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cultural_kingdom",
            name="kingdom_name",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=250,
                primary_key=True,
                serialize=False,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cultural_identity",
            name="ethnic_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cultures_app.ethnic_group",
            ),
        ),
        migrations.DeleteModel(
            name="Tribe",
        ),
        migrations.AddField(
            model_name="ethnicity",
            name="kingdom",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cultures_app.cultural_kingdom",
            ),
        ),
        migrations.AddField(
            model_name="ethnic_group",
            name="ethnicity_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cultures_app.ethnicity",
            ),
        ),
    ]
