# Generated by Django 4.2.5 on 2023-09-22 14:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cultures_app", "0002_ethnicity_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cultural_Identity",
            new_name="CulturalIdentity",
        ),
        migrations.RenameModel(
            old_name="Cultural_Kingdom",
            new_name="CulturalKingdom",
        ),
        migrations.RenameModel(
            old_name="Ethnic_Group",
            new_name="EthnicGroup",
        ),
        migrations.AlterModelOptions(
            name="culturalidentity",
            options={},
        ),
    ]
