# Generated by Django 4.2.6 on 2023-11-05 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cultures_app', '0002_remove_clan_images_remove_clan_videos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clan',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='clan',
            name='citation',
        ),
        migrations.RemoveField(
            model_name='clan',
            name='contributor_name',
        ),
        migrations.RemoveField(
            model_name='clan',
            name='date_entered',
        ),
        migrations.RemoveField(
            model_name='clan',
            name='image',
        ),
        migrations.RemoveField(
            model_name='clan',
            name='video',
        ),
        migrations.RemoveField(
            model_name='culturalkingdom',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='culturalkingdom',
            name='image',
        ),
        migrations.RemoveField(
            model_name='culturalkingdom',
            name='video',
        ),
        migrations.RemoveField(
            model_name='ethnicity',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='ethnicity',
            name='citation',
        ),
        migrations.RemoveField(
            model_name='ethnicity',
            name='contributor_name',
        ),
        migrations.RemoveField(
            model_name='ethnicity',
            name='date_entered',
        ),
        migrations.RemoveField(
            model_name='ethnicity',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ethnicity',
            name='video',
        ),
        migrations.AddField(
            model_name='ethnicgroup',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='culture_audio'),
        ),
        migrations.AddField(
            model_name='ethnicgroup',
            name='citation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ethnicgroup',
            name='contributor_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ethnicgroup',
            name='date_entered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ethnicgroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='culture_images'),
        ),
        migrations.AddField(
            model_name='ethnicgroup',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ethnicgroup',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='culture_videos'),
        ),
    ]
