# Generated by Django 4.2.6 on 2023-11-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultures_app', '0003_remove_clan_audio_remove_clan_citation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethnicity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
