# Generated by Django 4.2.5 on 2023-09-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultures_app', '0003_rename_cultural_identity_culturalidentity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clan',
            old_name='description',
            new_name='exceptional_male_names',
        ),
        migrations.RemoveField(
            model_name='clan',
            name='special_names',
        ),
        migrations.RemoveField(
            model_name='clan',
            name='spirituality',
        ),
    ]
