# Generated by Django 4.2.5 on 2023-09-26 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cultures_app', '0003_rename_cultural_identity_culturalidentity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clan',
            old_name='clan_leader_name',
            new_name='clan_based_cultural_sites',
        ),
        migrations.RenameField(
            model_name='clan',
            old_name='cultural_sites',
            new_name='current_clan_leader',
        ),
        migrations.RenameField(
            model_name='clan',
            old_name='description',
            new_name='reserved_names',
        ),
        migrations.RemoveField(
            model_name='clan',
            name='special_names',
        ),
        migrations.RemoveField(
            model_name='clan',
            name='spirituality',
        ),
        migrations.RemoveField(
            model_name='ethnicity',
            name='food',
        ),
    ]
