POST http://127.0.0.1:8000/login
Content-Type: application/json

{ "username": "pawu?7b23", "password":"pawukoru@"}

###

POST http://127.0.0.1:8000/signup/
Content-Type: application/json

{ 
"username": "paulaK", 
"password":"myPk$tar3", 
"email":"korup01@pfw.edu"
}

###

GET http://127.0.0.1:8000/test_token
Content-Type: application/json

{}