# Generated by Django 4.2.6 on 2023-10-26 17:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates whether this user should be treated as a FGF system Administrator.', verbose_name='FGF system Administrator status'),
        ),
        migrations.CreateModel(
            name='PasswordResetInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_code', models.CharField(default='000000', max_length=6, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2023, 10, 27, 17, 33, 24, 856157, tzinfo=datetime.timezone.utc))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth_app.user')),
            ],
            options={
                'verbose_name_plural': 'Password Reset Info',
                'ordering': ['user'],
            },
        ),
    ]
