# Generated by Django 4.2.6 on 2023-11-05 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_user_is_admin_passwordresetinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_contributor',
        ),
        migrations.AlterField(
            model_name='passwordresetinfo',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 5, 1, 58, 452349, tzinfo=datetime.timezone.utc)),
        ),
    ]
