# Generated by Django 4.2.6 on 2023-11-05 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_passwordresetinfo_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetinfo',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 7, 37, 24, 870107, tzinfo=datetime.timezone.utc)),
        ),
    ]
