# Generated by Django 4.2.6 on 2023-11-12 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_alter_passwordresetinfo_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetinfo',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 13, 6, 51, 10, 190523, tzinfo=datetime.timezone.utc)),
        ),
    ]
