# Generated by Django 4.2.6 on 2023-11-14 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_alter_passwordresetinfo_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetinfo',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 2, 51, 49, 472596, tzinfo=datetime.timezone.utc)),
        ),
    ]
