# Generated by Django 4.2.6 on 2023-11-14 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0015_alter_passwordresetinfo_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetinfo',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 4, 36, 50, 207686, tzinfo=datetime.timezone.utc)),
        ),
    ]
