# Generated by Django 4.2.6 on 2023-12-01 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicinalPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_issues', models.TextField()),
                ('part_used', models.CharField(blank=True, max_length=100, null=True)),
                ('preparation_steps', models.TextField()),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('contraindications', models.TextField()),
                ('shelf_life', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botanical_name', models.CharField(blank=True, max_length=100, null=True)),
                ('region_in_Uganda', models.CharField(blank=True, max_length=100, null=True)),
                ('habitat', models.CharField(blank=True, max_length=100, null=True)),
                ('life_form', models.CharField(choices=[('forest', 'Forest'), ('meadow', 'Meadow'), ('climber', 'Climber'), ('grassland', 'Grassland'), ('herb', 'Herb'), ('shrub', 'Shrub'), ('tree', 'Tree')], max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('social_value', models.TextField()),
                ('economical_value', models.TextField()),
                ('cultural_value', models.TextField()),
                ('other_value', models.TextField()),
                ('is_medicinal', models.BooleanField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plant_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='plant_videos/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='plant_audio/')),
                ('notes', models.TextField()),
                ('citation', models.CharField(max_length=255)),
                ('contributor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlantName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_language', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants_app.language')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants_app.plant')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='names',
            field=models.ManyToManyField(related_name='plant_names', through='plants_app.PlantName', to='plants_app.language'),
        ),
        migrations.CreateModel(
            name='MedicinalPlantName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants_app.language')),
                ('medicinal_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants_app.medicinalplant')),
            ],
        ),
        migrations.AddField(
            model_name='medicinalplant',
            name='names',
            field=models.ManyToManyField(related_name='medicinal_plant_names', through='plants_app.MedicinalPlantName', to='plants_app.language'),
        ),
        migrations.AddField(
            model_name='medicinalplant',
            name='plant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medicinal_info', to='plants_app.plant'),
        ),
    ]
