# Generated by Django 4.2.5 on 2023-10-05 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('life_form', models.CharField(choices=[('shrub', 'Shrub'), ('tree', 'Tree'), ('herb', 'Herb'), ('grass', 'Grass'), ('climber', 'Climber'), ('other', 'Other')], default='other', max_length=50)),
                ('other_life_form_description', models.CharField(blank=True, help_text='Specify other life form (if selected "Other")', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherValueDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_value', models.CharField(max_length=50)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=250)),
                ('scientific_name', models.CharField(max_length=250)),
                ('unique_habitat', models.CharField(max_length=250)),
                ('climate_impact', models.CharField(max_length=250)),
                ('research_notes', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='media_files')),
                ('videos', models.FileField(blank=True, null=True, upload_to='media_files')),
                ('audio', models.FileField(blank=True, null=True, upload_to='media_files')),
                ('citation', models.CharField(max_length=250)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('contributor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('life_form', models.ManyToManyField(blank=True, related_name='plants', to='plants_app.lifeform')),
                ('other_value_details', models.ManyToManyField(related_name='plants', to='plants_app.othervaluedetail')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regions', models.CharField(blank=True, choices=[('Northern Uganda', 'Northern Uganda'), ('West Nile', 'West Nile'), ('Central Uganda', 'Central Uganda'), ('Eastern Uganda', 'Eastern Uganda'), ('Western Uganda', 'Western Uganda'), ('All Regions', 'All Regions')], default='All Regions', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('ecological', 'Ecological'), ('social', 'Social'), ('economic', 'Economic'), ('nutritional', 'Nutritional'), ('other', 'Other')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ValueDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants_app.plant')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants_app.value')),
            ],
        ),
        migrations.CreateModel(
            name='PlantLocalName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_local_names', to='plants_app.plant')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='region',
            field=models.ManyToManyField(blank=True, related_name='plants', to='plants_app.region'),
        ),
        migrations.AddField(
            model_name='plant',
            name='values',
            field=models.ManyToManyField(related_name='plants', through='plants_app.ValueDetail', to='plants_app.value'),
        ),
        migrations.CreateModel(
            name='MedicinalPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicinal_values_entered', models.BooleanField(default=False)),
                ('health_issues', models.TextField(blank=True, help_text='Add multiple health issues, separated by commas')),
                ('part_used_for_health_issues', models.TextField(blank=True, help_text='Part of the plant used for each health issue')),
                ('preparation_steps', models.TextField(blank=True, help_text='Preparation steps for each health issue')),
                ('dosage', models.TextField(blank=True, help_text='Dosage for each health issue')),
                ('contraindications', models.TextField(blank=True, help_text='Contraindications for each health issue')),
                ('shelf_life', models.CharField(blank=True, help_text='Shelf life of the prepared medicine', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for medicinal values')),
                ('contributor_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plants_app.plant')),
            ],
        ),
    ]
