# Generated by Django 4.2.5 on 2023-10-11 17:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='languages',
        ),
        migrations.AddField(
            model_name='plant',
            name='botanical_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='names',
            field=models.ManyToManyField(related_name='plant_names', through='plants_app.PlantName', to='plants_app.language'),
        ),
        migrations.CreateModel(
            name='MedicinalPlantName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants_app.language')),
                ('medicinal_plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants_app.medicinalplant')),
            ],
        ),
        migrations.AddField(
            model_name='medicinalplant',
            name='names',
            field=models.ManyToManyField(related_name='medicinal_plant_names', through='plants_app.MedicinalPlantName', to='plants_app.language'),
        ),
    ]
