# Generated by Django 4.2.3 on 2023-10-01 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinalplant',
            name='medicinal_values_entered',
        ),
    ]
