# Generated by Django 4.2.3 on 2023-10-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0002_remove_medicinalplant_medicinal_values_entered'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinalplant',
            name='medicinal_values_entered',
            field=models.BooleanField(default=False),
        ),
    ]
