# Generated by Django 4.2.5 on 2023-09-28 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0003_rename_medicinal_plant_medicinalplant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='regions',
            new_name='habitat',
        ),
        migrations.AddField(
            model_name='plant',
            name='region',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
