# Generated by Django 4.2.6 on 2023-11-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0003_rename_region_plant_region_in_uganda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicinalplant',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicinalplant',
            name='part_used',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicinalplant',
            name='shelf_life',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medicinalplantname',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='botanical_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='habitat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plant_images/'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='life_form',
            field=models.CharField(choices=[('forest', 'Forest'), ('meadow', 'Meadow'), ('climber', 'Climber'), ('grassland', 'Grassland'), ('herb', 'Herb'), ('shrub', 'Shrub'), ('tree', 'Tree')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='region_in_Uganda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plantname',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
