# Generated by Django 4.2.6 on 2023-11-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0004_alter_language_name_alter_medicinalplant_dosage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
