# Generated by Django 4.2.3 on 2023-10-02 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0004_remove_plant_contributor_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantLocalName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_local_name', to='plants_app.plant')),
            ],
        ),
        migrations.DeleteModel(
            name='PlantName',
        ),
    ]
