# Generated by Django 4.2.3 on 2023-10-02 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0005_plantlocalname_delete_plantname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantlocalname',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_local_names', to='plants_app.plant'),
        ),
    ]
