# Generated by Django 4.2.3 on 2023-10-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0006_alter_plantlocalname_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
