# Generated by Django 4.2.6 on 2023-11-14 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0006_medicinalplant_is_medicinal_plant_is_medicinal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicinalplant',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='medicinalplant',
            name='is_medicinal',
        ),
        migrations.RemoveField(
            model_name='medicinalplant',
            name='notes',
        ),
    ]
