# Generated by Django 4.2.6 on 2023-11-14 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants_app', '0007_remove_medicinalplant_contributor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='botanical_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
