# Generated by Django 4.2.5 on 2023-09-18 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal_Classification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kingdom_name", models.CharField(max_length=250)),
                ("species", models.CharField(max_length=250)),
                ("number_of_species", models.IntegerField(default=1, null=True)),
                ("animal_class", models.CharField(max_length=250)),
                ("order", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("local_name", models.CharField(max_length=250)),
                ("english_name", models.CharField(max_length=250)),
                ("scientific_name", models.CharField(max_length=250)),
                ("description", models.CharField(max_length=250)),
                ("area_in_Uganda", models.CharField(max_length=250)),
                ("economic_value", models.CharField(max_length=250)),
                ("threats", models.CharField(max_length=250)),
                ("habitat", models.CharField(max_length=250)),
                ("notes", models.CharField(max_length=250)),
                ("images", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "videos",
                    models.FileField(blank=True, null=True, upload_to="media_files"),
                ),
                (
                    "audio",
                    models.FileField(blank=True, null=True, upload_to="media_files"),
                ),
                ("citation", models.CharField(max_length=250)),
                ("date_entered", models.DateTimeField(auto_now_add=True)),
                (
                    "animal_classification",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="animals_app.animal_classification",
                    ),
                ),
                (
                    "contributor_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["local_name"],
            },
        ),
    ]
