# Generated by Django 4.2.6 on 2023-11-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='animal',
            name='threats',
            field=models.TextField(),
        ),
    ]
