# Generated by Django 4.2.5 on 2023-09-19 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("animals_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="animal_classification",
        ),
        migrations.AddField(
            model_name="animal",
            name="animal_classifications",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="animals_app.animal_classification",
            ),
        ),
    ]
