# Generated by Django 4.2.5 on 2023-09-22 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("animals_app", "0002_remove_animal_animal_classification_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Animal_Classification",
            new_name="AnimalClassification",
        ),
    ]
