# Generated by Django 4.2.5 on 2023-10-20 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0002_remove_animal_animal_classification_and_more'),
        ('animals_app', '0002_rename_local_name_animallocalname_animal_name_and_more'),
    ]

    operations = [
    ]
