# Generated by Django 4.2.6 on 2023-11-05 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0002_alter_animal_description_alter_animal_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='citation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='animallocalname',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='animals_app.animal'),
        ),
    ]
